apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: catalogix-rolebinding
subjects:
- kind: ServiceAccount
  name: catalogix-sa
roleRef:
  kind: Role
  name: catalogix-role
  apiGroup: rbac.authorization.k8s.io
