apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalogix-sa
  annotations:
    # REQUIRED FOR IRSA
    # Full IAM role ARN is mandatory (account ID cannot be omitted)
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountId }}:role/{{ .Values.serviceAccount.irsaRoleName }}